
public enum GraimTalkType
{
    Empty,
    Tutorial,
    Tutorial_Stay,
    TutorialAgain,
    TutorialAgain_Stay,

    LIKE01_Hello,
    LIKE01_Money,
    LIKE01_Money_yes,
    LIKE01_Money_yes_guilty,
    LIKE01_Envy,
    LIKE01_Question,
    LIKE01_Interest,
    LIKE01_Interest_no,
    LIKE01_Interest_yes,

    LIKE02_Dog,
    LIKE02_Dog_no,
    LIKE02_Dog_yes,
    LIKE02_Secret,
    LIKE02_Drink,
    LIKE02_Drink_no,
    LIKE02_Drink_yes,
    LIKE02_Valentine,
    LIKE02_Accessories,

    LIKE03_Proposal,
    LIKE03_Proposal_no,
    LIKE03_Proposal_yes,
    LIKE03_Pride,
    LIKE03_Muscle,
    LIKE03_Muscle_yes,
    LIKE03_Muscle_yes_mock,
    LIKE03_Muscle_yes_mock_sorry,
    LIKE03_Muscle_yes_mock_fool,
    LIKE03_Muscle_yes_yes,
    LIKE03_Muscle_mock,
    LIKE03_Cheating,
    LIKE03_Date,
    LIKE03_Date_sea,
    LIKE03_Date_Mountain,

}
