
public enum LuxTalkType
{
    Empty,
    Tutorial,
    Tutorial_Stay,
    Graim,
    TutorialAgain,
    TutorialAgain_Stay,


    LIKE01_Hello,
    LIKE01_Hello_stay,
    LIKE01_Money,
    LIKE01_Money_no,
    LIKE01_Money_yes,
    LIKE01_Aroma,
    LIKE01_Aroma_ng,
    LIKE01_Aroma_ok,
    LIKE01_Aroma_ok_yes,
    LIKE01_Scandal,
    LIKE01_Scandal_no,
    LIKE01_Scandal_yes,
    LIKE01_Interest,
    LIKE01_Interest_no,
    LIKE01_Interest_yes,

    LIKE02_Hello,
    LIKE02_Date,
    LIKE02_Date_no,
    LIKE02_Date_yes,
    LIKE02_Fashion,
    LIKE02_Fashion_cool,
    LIKE02_Fashion_cute,
    LIKE02_Valentine,
    LIKE02_Photo,

    LIKE03_Proposal,
    LIKE03_Proposal_no,
    LIKE03_Proposal_mock,
    LIKE03_Envy,
    LIKE03_Gluttony,
    LIKE03_liking,
    LIKE03_liking_up,
    LIKE03_liking_down,
    LIKE03_Star,

    Present_Chocolate,
    Present_Chocolate_love,
    Present_Chocolate_mock,
    Present_Chocolate_mock_mock,
    Present_ChocolateAgain,
    Present_Tiramisu,
    Present_Tiramisu_no,
    Present_Tiramisu_yes,
    Present_Marronglacé,
    Present_Madeleine,
    Present_Macaron,
    Present_Donut,
    Present_Cupcake,
    Present_Cookie,
    Present_Caramel,
    Present_Candy,
    Present_Baumkuchen,
}
